
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR',
  REPORTER: 'REPORTER',
  READER: 'READER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const ArticleStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED'
} as const

export type ArticleStatus = (typeof ArticleStatus)[keyof typeof ArticleStatus]
